version: 2
updates:
  - package-ecosystem: "gradle"
    directory: /
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "skiko"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
